name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - Alpha
    tags:
      - "v*"
  pull_request_target:
    branches:
      - Alpha

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs:
          - { goos: darwin, goarch: arm64, output: arm64 }
          - { goos: darwin, goarch: amd64, output: amd64 }

          - { goos: linux, goarch: '386', output: '386' }
          - { goos: linux, goarch: amd64, output: x86_64 }
          - { goos: linux, goarch: amd64, goamd64: v3, output: x86_64_v3 }
          - { goos: linux, goarch: arm64, output: arm64 }
          - { goos: linux, goarch: arm, goarm: '7', output: armv7 }

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22

    - name: Set Time Variable
      run: |
        echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "BUILDTIME=$(date)" >> $GITHUB_ENV

    - name: Setup NDK
      if: ${{ matrix.jobs.goos == 'android' }}
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26c

    - name: build core
      env:
        GOOS: ${{matrix.jobs.goos}}
        GOARCH: ${{matrix.jobs.goarch}}
        GOAMD64: ${{matrix.jobs.goamd64}}
        GOARM: ${{matrix.jobs.arm}}
        GOMIPS: ${{matrix.jobs.mips}}
        CC: ${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{matrix.jobs.ndk}}-clang
        CGO_ENABLED: ${{matrix.jobs.cgo}}
      run: |
        go build -v -tags "with_gvisor" -trimpath -ldflags "-X 'github.com/metacubex/mihomo/constant.Version=${VERSION}' -X 'github.com/metacubex/mihomo/constant.BuildTime=${BUILDTIME}' -w -s -buildid="
        if [ "${GOOS}" = "windows" ]; then 
          mv mihomo.exe mihomo-${GOOS}-${{matrix.jobs.output}}-${VERSION}.exe && zip -r mihomo-${GOOS}-${{matrix.jobs.output}}-${VERSION}.zip mihomo-${GOOS}-${{matrix.jobs.output}}-${VERSION}.exe
        else 
          mv mihomo* mihomo-${GOOS}-${{matrix.jobs.output}}-${VERSION} &&  tar -czvf mihomo-${GOOS}-${{matrix.jobs.output}}-${VERSION}.tar.gz mihomo-${GOOS}-${{matrix.jobs.output}}-${VERSION}
        fi
        ls

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.jobs.goos }}-${{ matrix.jobs.output }}
        path: |
          mihomo*.tar.gz
          mihomo*.zip